### ISSUE TITLE
Move this repository to maps and keep git history

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/learn-anything-old#80]
Best we swap the two repos as the maps repo is obsolete with new release. 

Bonus points, we only have to focus on one repo going forward and the react components @nglgzz released.

**Comment by nglgzz** [comment]
We might want to move `la-map` into the repo aswell, as it's very specific to the learn anything website, and it would be difficult to generalize to be used outside it. For instance voting doesn't work if you're not logged in, but it wouldn't be safe to allow other websites managing the authentication.

**Comment by nikitavoloboev** [comment]
Yeah I agree. This sounds like a good idea.
