### ISSUE TITLE
Clean up Resources before release

### ISSUE THREAD

**Issue by nikitavoloboev** [learn-anything/learn-anything-old#81]
That includes : 

- [x] Swap all the years in resources from 17: to (2017)
  - This : `15: generative adversarial nets in tensorflow 🖋️` should become this `Generative adversarial nets in tensorflow (2015) 🖋️`
  
- [x] Uppercase all resources
  - I made a mistake with lowercasing everything, now I realise punctuation is there for a reason. 
  
These are the two major clean ups we should do before releasing the update because other people should be inspired by other resources in the database already to get the idea for what can be included.

Perhaps we can use regex to fix these issues. If anyone wishes to help with this or knows a good way to fix this. That would be amazing.

**Comment by nglgzz** [comment]
We should also remove all resources that have no text.

**Comment by nikitavoloboev** [comment]
Don't all resources have text?

**Comment by nglgzz** [comment]
Nope, we have some resources with no text. Usually (only?) on the root node of maps.

**Comment by nikitavoloboev** [comment]
Oh yeah. Those are usually links to subreddits and things. And the name is stripped because it is implicit from resources being attached to main node.

We have to be less implicit like that in our new design though.
